name: Merge Another Repo
on: 
 push:
    branches: [master1]
 pull_request:
    branches: [master]
 workflow_dispatch:  
jobs:
  runs-on: ubuntu-latest
    steps:
      - name: Clone supercharge website repository
        uses: actions/checkout@v2

      # This part here is cloning a second repository
      # While cloning the repository:
      #   - it clones the repo into the given `path`
      #   - it checks out the branch defined at `ref`
      - name: Clone supercharge docs repository
        uses: actions/checkout@v2
        with:
          repository: vishklearning/Demo-SF-GH 
          path: resources/docs/2.x
          ref: 2.x
     # - name: upload artiface
     #   uses: actions/upload-artifact@v3.1.2
     #  with: 
     #       name: TempArtifact
     #       path: force-app/
