name: Test Wrokflow With Deployment
on:
  push:
    branches: [master1]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
      # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
      - name: 'Installing sfdx git delta'
        run: | 
             echo y | sfdx plugins:install sfdx-git-delta
             sfdx plugins 
      - name: 'Get all test files in repo'
        run: |
              node ./parseAllTests.js              
              ALLTESTS=$(cat testsAll.txt)       
              echo "APEX_TESTS_ALL=$ALLTESTS" >> $GITHUB_ENV
              echo ${{ github.event.push.head.sha }}
      - name: Check APEX
        uses: legetz/setup-pmd@v6.48
      - run: pmd --dir ./force-app/main/default/classes -R category/apex/design.xml      
      - name: 'Create delta packages for new, modified or deleted metadata'
        run: | 
            mkdir changed-sources
            sfdx sgd:source:delta --to "HEAD" --from $(git merge-base HEAD origin/main) --output changed-sources/ --generate-delta --source force-app/
      - name: upload artiface
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: TempArtifact
          path: force-app/
  SonarScan:
    needs: Build
    name: SonarCloud    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                   # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
      # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
      - name: 'Installing sfdx git delta'
        run: | 
             echo y | sfdx plugins:install sfdx-git-delta
             sfdx plugins 
      - name: 'force logout'
        run: sfdx force:auth:logout --all --noprompt
      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.Dev_URL}} > ./Dev_URL.txt
          echo ${{ secrets.Dev_URL}}
      - name: Get Auth URL
        run:  sfdx auth:web:login -i ${{ secrets.Client_ID}}  --instance-url=${{secrets.Instance_URL}}
        # sfdx force:org:display -u MyAliasName --verbose
      - name: Authenticate to target Org
        run: sfdx auth:sfdxurl:store -f ./Dev_URL.txt -s -a targetOrg
      - name: Deployment - run all tests
        run: >
          sfdx force:source:deploy -p "force-app" --checkonly --testlevel RunLocalTests --json
